exports.install = require('./install')
exports.analyze = require('./analyze')
exports.updateDep = require('./update-dep')
exports.normalize = require('./normalize')
exports.prune = require('./prune')
exports.custom = require('./custom')
